#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use TextAnalysis\Console\Commands\NltkPackageListCommand;
use TextAnalysis\Console\Commands\NltkPackageInstallCommand;
use TextAnalysis\Console\Commands\StopWordsCommand;
use TextAnalysis\Console\Commands\VocabSizeCommand;
use TextAnalysis\Console\Commands\NltkPackageInstallAllCommand;

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new NltkPackageListCommand());
$app->add(new NltkPackageInstallCommand());
$app->add(new StopWordsCommand());
$app->add(new VocabSizeCommand());
$app->add(new NltkPackageInstallAllCommand());

$app->run();