#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use TextAnalysis\Console\Commands\NltkPackageListCommand;
use TextAnalysis\Console\Commands\NltkPackageInstallCommand;

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new NltkPackageListCommand());
$application->add(new NltkPackageInstallCommand());
$application->run();